name: Deploy Angular App to Firebase Hosting

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist/

      - name: Determine Firebase Project ID
        id: firebase_project_id
        run: |
          # We use github.ref to precisely determine the branch.
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "project_id=la-maison-atazik" >> $GITHUB_OUTPUT # Production project ID
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "project_id=la-maison-atazik-staging" >> $GITHUB_OUTPUT # Staging project ID
          else
            echo "No matching branch for deployment, skipping."
            exit 0 # Exit successfully if no deployment is needed for this branch
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting and Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${HOME}/gcp-key.json"
        run: firebase deploy --only hosting,functions --project ${{ steps.firebase_project_id.outputs.project_id }}
