name: Deploy Angular App to Firebase Hosting

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      configuration: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist/

      - name: Determine Environment
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
            echo "firebase_project=la-maison-atazik" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            echo "env=staging" >> $GITHUB_OUTPUT
            echo "firebase_project=la-maison-atazik-staging" >> $GITHUB_OUTPUT
          fi

      - name: Authenticate and Deploy to Firebase Hosting
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          npm install -g firebase-tools
          echo "$FIREBASE_SERVICE_ACCOUNT" > ${HOME}/firebase.json
          export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/firebase.json"
          firebase deploy --only hosting:${{ steps.env.outputs.env }} --project ${{ steps.env.outputs.firebase_project }}
          firebase deploy --only functions --project ${{ steps.env.outputs.firebase_project }}
